### PR TITLE
Highlight "Start" in top nav for top level pages.

### PR DESCRIPTION
**Pull request by th-h**
/downloads.html, /features.html and /team.html
pages should have the "Start" item in the top
navigation highlighted so you know where you
are in the menu structure of the site.

Signed-off-by: Thomas Hochstein thh@inter.net

### CODE REVIEW

**Comment by th-h** [comment]
Just a suggestion - don't know if you like it. I would. :smile:

**Comment by yellowled** [comment]
But you're not on “Start”. You're on “Downloads”, “Features” or “Developer Team”. I agree that it looks a tad strange, but `index.html` is not the current page on either of these pages.

**Comment by th-h** [comment]
> But you're not on “Start”. You're on “Downloads”, “Features” or “Developer Team”.

... which are pages in the "Start" category, as I see it.

> I agree that it looks a tad strange, but index.html is not the current page on either of these pages.

Fair enough. :) I still miss a visual hint where you are when on one of these pages.

One could think about replacing "Start" with some other generic term that would fit better ... or we just leave it as it is.

**Comment by th-h** [comment]
While thinking a bit more about that ...

What about a breadcrumb navigation? That would show "where you are", and it would help on some deeper nested documentation pages, too. On /docs/users/getting-started/embedding.html, you have no idea that you are on a page "below" the "Getting started" link in the sidebar.

**Comment by yellowled** [comment]
> ... which are pages in the "Start" category, as I see it.

There is no “Start category”, there ist just a page “Start” (which the menu item “Start” links to).

As I said, I get what you mean visually, but I'm not sure if that is possible with the constraints of Jekyll. Same is true for a breadcrumb navigation. Sure, we can always add it manually or hardcoded, but that's a looooot of work and maintenance …

**Comment by yellowled** [comment]
I suggest to add an issue for adding a breadcrumb nav and closing this pull request, if that's okay with you?

**Pull request closed without merging**
