### PR TITLE
Restructure files for use with Jeykll

### PR DESCRIPTION
**Pull request by yellowled**
- Proposed site structure:
  https://gist.github.com/yellowled/af4b8a85b7f6eda632c7
- Deleted all (empty) *.html files
- docs-landing-page.md is now index.md

### CODE REVIEW

**Comment by yellowled** [comment]
@garvinhicking @onli 

This is what we discussed in Mumble today, see

https://gist.github.com/yellowled/af4b8a85b7f6eda632c7

for reference. I hope I didn't forget something, and I realize it's hard to see what I did in the diff here on GitHub. You can check out the branch `jekyll-restructure` locally as well, maybe that's easier to compare.

One thing I stumbled across while doing this which we did not discuss: Do we want (sub-)folders only for sections of the site that actually _have_ multiple pages or  do we want it always?

For example: should the menu item _Team_ be
- `/team.md` (which would ultimately become `http://s9y.org/team.html`)
- `/team/index.md` (which would become `http://s9y.org/team/index.html/` or `http://s9y.org/team/`)

**Comment by onli** [comment]
> Do we want (sub-)folders only for sections of the site that actually have multiple pages or do we want it always?

I see no harm in either. Only when we have multiple pages feels a bit cleaner.

**Comment by yellowled** [comment]
In that case, it would have been nice to leave the PR open so I can add the changes needed for that to the PR, but nevermind. I'll just do it in `master`. :)

**Comment by onli** [comment]
Was too happy to see the changes ;)

**Pull request merged**
