### PR TITLE
Revamped 'Features' section on start page

### PR DESCRIPTION
**Pull request by yellowled**
- Use 4 items in the features section instead of 6
- Use icons next to headings instead of screenshots next to copy
- Add a button link to separate 'Features' page
- Add new icons assets
- Remove obsolete screenhot image assets

### CODE REVIEW

**Comment by yellowled** [comment]
Everyone, please leave this open for @onli to review and act on it.

**Comment by yellowled** [comment]
@garvinhicking Any chance you could give us a quick feedback on what you prefer (visually, the actual content is still subject to change)?
1. [revamped version](https://www.dropbox.com/s/5mjssvaqd45f7yk/Screenshot%202015-12-08%2012.41.27.png?dl=0) (Screenshot only of the relevant portion of the page)
2. the corresponding section of http://docs.s9y.org/index.html

**Comment by garvinhicking** [comment]
(Sorry, really busy right now, having a [flat]deadlining project on 18.12)

Hard to say. I like the brevity of the screenshot version, it's easier on the eye. However, it's also bland and generic. Well, dunno. I'm undecided, I probably can get along fine with both versions...

**Comment by yellowled** [comment]
Thanks for taking the time anyway. Shoo-shoo. ;-)

**Pull request merged**
